# -*- coding: utf-8 -*-
"""Data_Retrival_COC_API_Prog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz1W2-kYe2j3Wl_NDaSOJnGMPeZMheFN
"""

import requests
import pandas as pd

# URL of the API
url = 'https://coc-ancient-ruins-website.onrender.com/api/mem'

# Fetching the data
response = requests.get(url)
data = response.json()

# Assuming the JSON data is a list of dictionaries
df = pd.DataFrame(data)

# Saving the data to an Excel file
output_xlsx = 'mem_data.xlsx'
output_csv = 'mem_data.csv'
output_json = 'mem_data.json'
df.to_excel(output_xlsx, index=False)
df.to_csv(output_csv, index=False)
df.to_json(output_json, orient='records', lines=True)

print(f"Data saved to {output_xlsx} , {output_csv} and {output_json}")

import requests
import pandas as pd

# URL of the API
url = 'https://coc-ancient-ruins-website.onrender.com/api/fmem'

# Fetching the data
response = requests.get(url)
data = response.json()

# Assuming the JSON data is a list of dictionaries
df = pd.DataFrame(data)

# Saving the data to an Excel file
output_xlsx = 'fmem_data.xlsx'
output_csv = 'fmem_data.csv'
output_json = 'fmem_data.json'
df.to_excel(output_xlsx, index=False)
df.to_csv(output_csv, index=False)
df.to_json(output_json, orient='records', lines=True)

print(f"Data saved to {output_xlsx} , {output_csv} and {output_json}")